export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  ROLE_NOT_CONFIGURED: "ROLE_NOT_CONFIGURED",

  UNAUTHORIZED: "UNAUTHORIZED",

  FORBIDDEN: "FORBIDDEN",

  INVALID_TOKEN: "INVALID_TOKEN",

  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",

  SESSION_REVOKED: "SESSION_REVOKED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;